parameters:
  timezone: '%env(TIMEZONE)%'
  fake_smtp_api.base_uri: '%env(FAKE_SMTP_API_URI)%'
  mqtt.client_id: '%env(MQTT_CLIENT_ID)%'
  mqtt.broker: '%env(MQTT_BROKER)%'
  mqtt.port: '%env(MQTT_PORT)%'
  mqtt.topic: '%env(MQTT_TOPIC)%'
  mqtt.username: '%env(MQTT_USERNAME)%'
  mqtt.password: '%env(MQTT_PASSWORD)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  ZoiloMora\HikvisionCommunicator\:
    resource: '../src/*'
    exclude: '../src/{Kernel.php}'

  ZoiloMora\HikvisionCommunicator\Entrypoint\Console\:
    resource: '../src/Entrypoint/Console/*'
    tags: ['console.command']

  http.client.fake_smtp:
    class: GuzzleHttp\Client
    arguments:
      - base_uri: '%fake_smtp_api.base_uri%'

  mqtt.client:
    class: Mosquitto\Client
    arguments:
      $id: '%mqtt.client_id%'
      $cleanSession: true

  ZoiloMora\HikvisionCommunicator\Infrastructure\Domain\Model\Event\FakeSmtpEventRepository:
    class: ZoiloMora\HikvisionCommunicator\Infrastructure\Domain\Model\Event\FakeSmtpEventRepository
    arguments:
      $client: '@http.client.fake_smtp'
      $timezone: '%timezone%'

  ZoiloMora\HikvisionCommunicator\Infrastructure\Domain\Service\Event\MqttPublisher:
    class: ZoiloMora\HikvisionCommunicator\Infrastructure\Domain\Service\Event\MqttPublisher
    arguments:
      $client: '@mqtt.client'
      $broker: '%mqtt.broker%'
      $port: '%mqtt.port%'
      $username: '%mqtt.username%'
      $password: '%mqtt.password%'
      $topic: '%mqtt.topic%'
